### ISSUE TITLE
在SFO2创建了一个，但还是爬着就停住了

### ISSUE THREAD

**Issue by zplzpl** [derekhe/ProxyPool#2]
我DO上购买SFO2区域的服务器，但是确实，跑着跑着会出现停住的现象，爬取记录数不到几百

是否还有什么配置？

有时候开始跑还会遇到下面的错误：

aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host myexternalip.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')]

**Comment by derekhe** [comment]
我的测试结果是一般10多分钟后就有上千个代理，1个小时之后有几千个，每天大约1万个左右
你可以自行增加一些调试信息看看是否有什么其他问题。

**Comment by zplzpl** [comment]
可以问一下，你使用的proxybroker的版本吗？

**Comment by derekhe** [comment]
用的是这个仓库中我改过的版本，原版的只能拉到不多的代理。

**Comment by derekhe** [comment]
问题有解决么？

**Comment by zplzpl** [comment]
感谢你的工作，我并没有解决这个问题。我归纳了一下问题：

1. 我对python编译不足够了解，无法使用内置的lib/proxybroker，我使用了pip3 install proxybroker
2. 关于python3 ./server/proxy.py 运行会停止住的问题，我仍持疑问，我等待了很久（1小时以上），并没有任何的响应，这个是原版也会遇到这个问题，我提了issue但官方repo还没回复
3. 关于数量目前，爬取500多个，经过逻辑过滤后，我在redis里面仍只有不到100个，如果作者能有1W+，我想如果能有个明细教程会更好

目前我主要采用的golang来爬取，因为我的需求也是比较简单，不需要大型爬虫框架，所以选择了熟悉的语言栈来做，失败重试、代理池封装也做了，爬取任务监控也做好了。就是这个代理池的资源目前还没有找到免费比较好的。

我爬取的网站是对国内IP屏蔽的，所以我这边倾向也是国外的代理资源。

**Comment by derekhe** [comment]
我明白了，你直接pip3 install proxybroker装的是官方的，是有问题的，我的lib/proxybroker里面做了一些修改。
请直接在根目录下面用docker-compose up试试。
如果非要单独运行，可以用pipenv run python3 server/proxy.py，这样通过pipenv可以将./lib/proxybroker的版本安装好。

**Comment by zplzpl** [comment]
好的，我之前没有使用docker && docker-compose，是担心，在VPS占用更多的资源，但在你的建议下，我决定还是采用docker-compose up的方式来跑一下。

但我遇到下面这个问题：

Errors were encountered while processing:
 imagemagick-6-common
 libmagickcore-6.q16-3:amd64
 libmagickwand-6-headers
 libmagickcore-6-arch-config:amd64
 imagemagick-6.q16
 libmagickwand-dev
 libmagickwand-6.q16-dev:amd64
 libmagickcore-6.q16-3-extra:amd64
 libmagickwand-6.q16-3:amd64
 imagemagick
 libmagickcore-6.q16-dev:amd64
 libmagickcore-6-headers
E: Sub-process /usr/bin/dpkg returned an error code (1)
ERROR: Service 'proxy' failed to build: The command '/bin/sh -c apt update && apt upgrade -y && apt install python3.7-dev libffi-dev -y' returned a non-zero code: 100


我重新用了pipenv run的方式去跑，但是一样遇到了，跑一断时间，会卡住。

如果你需要我的SSH信息，我可以发给你看看。

**Comment by derekhe** [comment]
我看了，已经重现了问题，有可能是某些包已经更新导致。我在重新测试看看。

**Comment by derekhe** [comment]
我把构建修复了，但是还是会卡死……
这个库我之前也遇到了一些问题的，很奇怪，有时间再修一下

**Comment by zplzpl** [comment]
谢谢

**Comment by yucongo** [comment]
你可以先卸掉系统的proxybroker，再在 lib 目录里运行
python3 setup.py develop

然后再启动 redis、运行 python3 server\proxy.py 以及 python3 server\proxy-server.py, 过一阵就可以在端口 80/proxy.json 或 redis里拿到代理了。至少ubuntu 18可用。Win10好像不行，aiohttp出错。

proxy.py 有时会死挂掉。中断后再运行有可以继续一阵。

**Comment by splinter21** [comment]
同停住了

**Comment by splinter21** [comment]
同爬了几分钟停住了，然后再也没有更新
直接docker-compose up开着的

**Comment by derekhe** [comment]
这个具体什么原因我还是不清楚……

**Comment by splinter21** [comment]
ok了。。。
最后我没用它默认的代码，在proxybrother外面自己写个调providers里面的get_proxies。。。
所有一波大概能有3.3万以上（不检查）
检查的脚本自己写好了

**Comment by gMan1990** [comment]
同，爬着爬着就不动了

**Comment by 99103248** [comment]
> ok了。。。
> 最后我没用它默认的代码，在proxybrother外面自己写个调providers里面的get_proxies。。。
> 所有一波大概能有3.3万以上（不检查）
> 检查的脚本自己写好了

请问下你是怎么调用的

**Comment by derekhe** [comment]
@splinter21 大家可以参考一下他的做法，应该是可以。我今天创建了一个服务器在上面跑了一下，发现很多的列表网站已经不可以用了，还有检查的时候会调用到一些网站检查IP的真伪，这些服务也有一些问题。
