### ISSUE TITLE
PROVIDERS里的先后顺序是否和爬取顺序有关？

### ISSUE THREAD

**Issue by gMan1990** [derekhe/ProxyPool#4]
https://github.com/derekhe/ProxyPool/blob/9845049cdba0b3215f1b8aa70c713d024a5e7902/lib/proxybroker/providers.py#L838
PROVIDERS里越靠前，越先爬？

**Comment by derekhe** [comment]
这个不是太明确，这部分要看作者怎么实现的。

**Comment by gMan1990** [comment]
把日志开到最大，看到确实是`PROVIDERS里越靠前，越先爬` (当然并不是说绝对的按顺序)
